PORT:8080
HTTP_WORKERS:2

PROXY_PART:http://localhost:8081
API_URL:http://localhost:8080
FRONTEND_URL:http://localhost:3000
DISABLE_REGISTRATION:false
CONSENT_COOKIE:true

hibernate.connection.url:jdbc:postgresql://postgres:5432/piped
hibernate.connection.driver_class:org.postgresql.Driver
hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username:piped
hibernate.connection.password:piped
