/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as EmailVerificationImport } from './routes/emailVerification'
import { Route as AuthImport } from './routes/auth'
import { Route as SideAndNavBarsPageLayoutImport } from './routes/_sideAndNavBarsPageLayout'
import { Route as IndexImport } from './routes/index'
import { Route as SideAndNavBarsPageLayoutWorkoutImport } from './routes/_sideAndNavBarsPageLayout/workout'
import { Route as SideAndNavBarsPageLayoutTasksImport } from './routes/_sideAndNavBarsPageLayout/tasks'
import { Route as SideAndNavBarsPageLayoutNutritionImport } from './routes/_sideAndNavBarsPageLayout/nutrition'
import { Route as SideAndNavBarsPageLayoutHomeImport } from './routes/_sideAndNavBarsPageLayout/home'
import { Route as SideAndNavBarsPageLayoutFinancesImport } from './routes/_sideAndNavBarsPageLayout/finances'
import { Route as SideAndNavBarsPageLayoutCalendarImport } from './routes/_sideAndNavBarsPageLayout/calendar'
import { Route as SideAndNavBarsPageLayoutAboutImport } from './routes/_sideAndNavBarsPageLayout/about'
import { Route as SideAndNavBarsPageLayoutNutritionIndexImport } from './routes/_sideAndNavBarsPageLayout/nutrition/index'
import { Route as SideAndNavBarsPageLayoutNutritionFoodDiaryImport } from './routes/_sideAndNavBarsPageLayout/nutrition/foodDiary'

// Create/Update Routes

const TestRoute = TestImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const EmailVerificationRoute = EmailVerificationImport.update({
  path: '/emailVerification',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const SideAndNavBarsPageLayoutRoute = SideAndNavBarsPageLayoutImport.update({
  id: '/_sideAndNavBarsPageLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SideAndNavBarsPageLayoutWorkoutRoute =
  SideAndNavBarsPageLayoutWorkoutImport.update({
    path: '/workout',
    getParentRoute: () => SideAndNavBarsPageLayoutRoute,
  } as any)

const SideAndNavBarsPageLayoutTasksRoute =
  SideAndNavBarsPageLayoutTasksImport.update({
    path: '/tasks',
    getParentRoute: () => SideAndNavBarsPageLayoutRoute,
  } as any)

const SideAndNavBarsPageLayoutNutritionRoute =
  SideAndNavBarsPageLayoutNutritionImport.update({
    path: '/nutrition',
    getParentRoute: () => SideAndNavBarsPageLayoutRoute,
  } as any)

const SideAndNavBarsPageLayoutHomeRoute =
  SideAndNavBarsPageLayoutHomeImport.update({
    path: '/home',
    getParentRoute: () => SideAndNavBarsPageLayoutRoute,
  } as any)

const SideAndNavBarsPageLayoutFinancesRoute =
  SideAndNavBarsPageLayoutFinancesImport.update({
    path: '/finances',
    getParentRoute: () => SideAndNavBarsPageLayoutRoute,
  } as any)

const SideAndNavBarsPageLayoutCalendarRoute =
  SideAndNavBarsPageLayoutCalendarImport.update({
    path: '/calendar',
    getParentRoute: () => SideAndNavBarsPageLayoutRoute,
  } as any)

const SideAndNavBarsPageLayoutAboutRoute =
  SideAndNavBarsPageLayoutAboutImport.update({
    path: '/about',
    getParentRoute: () => SideAndNavBarsPageLayoutRoute,
  } as any)

const SideAndNavBarsPageLayoutNutritionIndexRoute =
  SideAndNavBarsPageLayoutNutritionIndexImport.update({
    path: '/',
    getParentRoute: () => SideAndNavBarsPageLayoutNutritionRoute,
  } as any)

const SideAndNavBarsPageLayoutNutritionFoodDiaryRoute =
  SideAndNavBarsPageLayoutNutritionFoodDiaryImport.update({
    path: '/foodDiary',
    getParentRoute: () => SideAndNavBarsPageLayoutNutritionRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_sideAndNavBarsPageLayout': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/emailVerification': {
      preLoaderRoute: typeof EmailVerificationImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/_sideAndNavBarsPageLayout/about': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutAboutImport
      parentRoute: typeof SideAndNavBarsPageLayoutImport
    }
    '/_sideAndNavBarsPageLayout/calendar': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutCalendarImport
      parentRoute: typeof SideAndNavBarsPageLayoutImport
    }
    '/_sideAndNavBarsPageLayout/finances': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutFinancesImport
      parentRoute: typeof SideAndNavBarsPageLayoutImport
    }
    '/_sideAndNavBarsPageLayout/home': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutHomeImport
      parentRoute: typeof SideAndNavBarsPageLayoutImport
    }
    '/_sideAndNavBarsPageLayout/nutrition': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutNutritionImport
      parentRoute: typeof SideAndNavBarsPageLayoutImport
    }
    '/_sideAndNavBarsPageLayout/tasks': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutTasksImport
      parentRoute: typeof SideAndNavBarsPageLayoutImport
    }
    '/_sideAndNavBarsPageLayout/workout': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutWorkoutImport
      parentRoute: typeof SideAndNavBarsPageLayoutImport
    }
    '/_sideAndNavBarsPageLayout/nutrition/foodDiary': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutNutritionFoodDiaryImport
      parentRoute: typeof SideAndNavBarsPageLayoutNutritionImport
    }
    '/_sideAndNavBarsPageLayout/nutrition/': {
      preLoaderRoute: typeof SideAndNavBarsPageLayoutNutritionIndexImport
      parentRoute: typeof SideAndNavBarsPageLayoutNutritionImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SideAndNavBarsPageLayoutRoute.addChildren([
    SideAndNavBarsPageLayoutAboutRoute,
    SideAndNavBarsPageLayoutCalendarRoute,
    SideAndNavBarsPageLayoutFinancesRoute,
    SideAndNavBarsPageLayoutHomeRoute,
    SideAndNavBarsPageLayoutNutritionRoute.addChildren([
      SideAndNavBarsPageLayoutNutritionFoodDiaryRoute,
      SideAndNavBarsPageLayoutNutritionIndexRoute,
    ]),
    SideAndNavBarsPageLayoutTasksRoute,
    SideAndNavBarsPageLayoutWorkoutRoute,
  ]),
  AuthRoute,
  EmailVerificationRoute,
  TestRoute,
])

/* prettier-ignore-end */
