// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackYourLife.Modules.Youtube.Infrastructure.Data;

#nullable disable

namespace TrackYourLife.Modules.Youtube.Infrastructure.Migrations
{
    [DbContext(typeof(YoutubeWriteDbContext))]
    [Migration("20260529134245_AddSettingsPasswordResetEmailSentAtUtc")]
    partial class AddSettingsPasswordResetEmailSentAtUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Youtube")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.DailyCategoryWatchCounters.DailyCategoryWatchCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VideosWatchedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("YoutubeCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Date", "YoutubeCategoryId")
                        .IsUnique();

                    b.ToTable("DailyCategoryWatchCounter", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.WatchedVideos.WatchedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("WatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique();

                    b.ToTable("WatchedVideo", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.YoutubeCategories.YoutubeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVideosPerDay")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("YoutubeCategory", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.YoutubeChannels.YoutubeChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("YoutubeCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "YoutubeCategoryId");

                    b.HasIndex("UserId", "YoutubeChannelId")
                        .IsUnique();

                    b.ToTable("YoutubeChannel", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.YoutubePlaylists.YoutubePlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("YoutubePlaylist", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.YoutubePlaylists.YoutubePlaylistVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("VideoId");

                    b.Property<Guid>("YoutubePlaylistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("YoutubePlaylistId", "YoutubeId")
                        .IsUnique();

                    b.ToTable("YoutubePlaylistVideo", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.YoutubeSettings.YoutubeSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettingsPasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("SettingsPasswordResetEmailSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("YoutubeSettings", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.SharedLib.Domain.OutboxMessages.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<bool>("IsDirectEvent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "Youtube");
                });

            modelBuilder.Entity("TrackYourLife.Modules.Youtube.Domain.Features.YoutubePlaylists.YoutubePlaylistVideo", b =>
                {
                    b.HasOne("TrackYourLife.Modules.Youtube.Domain.Features.YoutubePlaylists.YoutubePlaylist", null)
                        .WithMany()
                        .HasForeignKey("YoutubePlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
