name: Build Frontend

on:
  workflow_dispatch: # Enable manual triggering
  push:
    branches:
      - main
    paths:
      - "ClientApp/**"
  pull_request:
    paths:
      - "ClientApp/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "ClientApp/package-lock.json"

      - name: Install dependencies
        working-directory: ClientApp
        run: npm ci

      - name: Run linting
        working-directory: ClientApp
        run: npm run lint

      - name: Build project
        working-directory: ClientApp
        env:
          VITE_HOST: "127.0.0.1"
          VITE_API_PATH: "http://localhost:5000"
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ClientApp/dist
          retention-days: 7
